- name: Install CloudWatch Agent
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Download CloudWatch Agent installer
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: ./amazon-cloudwatch-agent.deb
        mode: '0644'

    - name: Install CloudWatch Agent
      shell: sudo dpkg -i -E ./amazon-cloudwatch-agent.deb

    - name: Copy config file
      template:
        src: config.json
        dest: /home/ubuntu/config.json

    - name: Moving config
      shell: sudo mv /home/ubuntu/config.json /opt/aws/amazon-cloudwatch-agent/bin

    - name: Starting cwagent
      shell: sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json